source 'https://cdn.cocoapods.org/'

workspace './DemoNestViewController.xcworkspace'
project './DemoNestViewController.xcodeproj', 'Debug' => :debug, 'Release' => :release

platform :ios, '11.0'
use_frameworks!
# ignore all warnings from all dependencies
inhibit_all_warnings!

def ui_pods
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'JXCategoryView'
end

target 'DemoNestViewController' do
  ui_pods
end